# Generated by Django 4.1.7 on 2023-02-24 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Encryption', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encrypt',
            name='file',
            field=models.FileField(blank=True, upload_to='file'),
        ),
    ]
