# Generated by Django 4.1 on 2023-02-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Encryption", "0002_alter_encrypt_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="encrypt",
            name="file",
            field=models.FileField(blank=True, upload_to=""),
        ),
    ]
